name = "Photutils"
uuid = "0af7feb3-9ebb-49d6-ba68-d375c82e2d55"
version = "1.0.0-DEV"
authors = ["Decrescent398 <ganeshhgunda123@gmail.com> and contributors"]

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Reexport = "1.2.2"
StaticArrays = "1.9.15"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
