name = "Photutils"
uuid = "0af7feb3-9ebb-49d6-ba68-d375c82e2d55"
authors = ["Decrescent398 <ganeshhgunda123@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
